import Head from 'next/head';
import { LazyImage } from '@/components/LazyImage';
import { useState , MouseEventHandler} from 'react';
import {random} from 'lodash';//for typing @types/library name/file
//definitely Types repo for libraries with TYPES TS

const myRandom = (): number => random(1, 123);
const generateRandomId=(): string => {
  const alphabet = "abcdefghijklmnopqrstuvwxyz0123456789";
  let id = "";

  for (let i = 0; i < 10; i++) {
    const randomIndex = Math.floor(Math.random() * alphabet.length);
    id += alphabet[randomIndex];
  }

  return id;
}

export default function Home() {
  const [images, setImages] = useState<IImageItem[]>([]);
 
  const addFox:MouseEventHandler<HTMLButtonElement> = () => {
      
    const newSrc:IImageItem = {id: generateRandomId(), url:`https://randomfox.ca/images/${myRandom()}.jpg`}
    
    setImages([...images, newSrc]); //DONT REMEMBER USE SPREAD AND REST
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-2xl text-yellow-600'>hola mundo</h1>
        <button onClick={()=> addFox() }>add new fox</button>
        {
          images.map(({url, id}, index)=>( //fine destructuring of map REMEMBER
              <div className='p-4' key={id}>
                <LazyImage 
                image={url} 
                onLazyLoad={(img) => {
                  console.log(`Image #${index + 1} cargada. Nodo:`, img);
                }}
                className="rounded-xl bg-slate-400 w-full h-full"/>
              </div>
          ))
        }
      </main>
    </>
  )
}
