import Head from 'next/head';
import { LazyImage } from '@/components/LazyImage';
import { useState , MouseEventHandler} from 'react';

interface arrayFox{
  id:string,
  url:string
}
type ImageItem = {id:string, url: string} 
//can use interface or type, type represent the minimal representation of object

const random = (): number => Math.floor(Math.random() * 123) + 1;

export default function Home() {
  const [images, setImages] = useState<ImageItem[]>([]);
 
  const addFox:MouseEventHandler<HTMLButtonElement> = () => {
      
    const newfox:ImageItem = {id:'...', url:`https://randomfox.ca/images/${random()}.jpg`}
    
    setImages([...images, newfox]); //DONT REMEMBER USE SPREAD AND REST
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-2xl text-yellow-600'>hola mundo</h1>
        <button onClick={()=> addFox() }>add new fox</button>
        {
          images.map(({url, id})=>( //fine destructuring of map REMEMBER
              <div className='p-4' key={id}>
                <LazyImage 
                image={url} 
                onClick={()=> console.log('pingaloca')}
                className="rounded-xl bg-slate-400"/>
              </div>
          ))
        }
      </main>
    </>
  )
}
